package local.jrmmba.points.models;

import javax.persistence.*;

/**
 * The entity defining and allowing interactions with the Expenditure table
 */
@Entity
@Table(name = "spends")
public class Spend
        extends Auditable
{
    /**
     * The primary key (long) of this expenditure
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long spendId;

    /**
     * The points (int) being spent in this transaction
     */
    private int points;

    /**
     * Creates a new spend transaction
     *
     * @param points the points being spent in this transaction
     */
    public Spend(int points)
    {
        this.points = points;
    }

    /**
     * Default constructor as required by the JPA
     */
    public Spend()
    {
    }

    /**
     * Getter for primary key for the spend table
     *
     * @return the primary key for this spend row
     */
    public long getSpendId()
    {
        return spendId;
    }

    /**
     * Setter for the primary key of this spend transaction . Normally the primary key is automatically
     * generated by the application. However, in some testing instances, a primary key must be assigned.
     *
     * @param spendId the new primary key for this spend transaction.
     */
    public void setSpendId(long spendId)
    {
        this.spendId = spendId;
    }

    /**
     * Getter for the points spent in this row
     *
     * @return the points spent
     */
    public int getPoints()
    {
        return points;
    }

    /**
     * Setter for the points spent in this row
     *
     * @param points the new amount of points being spent
     */
    public void setPoints(int points)
    {
        this.points = points;
    }
}
